spring:
  application:
    name: SpringLab2
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
logging:
  file:
    name: logs/bankist.log
  level:
    root: INFO
    ua.opnu.bankist: DEBUG
  config: classpath:logback-spring.xml